### ISSUE TITLE
Unable to install with the composer instructions

### ISSUE THREAD

**Issue by johnsoncam** [yiisoft/db-mssql#3]
### What steps will reproduce the problem?
composer require --prefer-dist yiisoft/yii2-mssql "~1.0.0"

### What do you get instead?
Could not find a matching version of package yiisoft/yii2-mssql. Check the package spelling, your version constraint and that the package is availa
  ble in a stability which matches your minimum-stability (stable).
### Additional info

| Q                    | A
| -------------------- | ---
| Yii version          | 2.?
| Yii MSSQL version    |
| MSSQL Server version |
| PHP version          | 7.2
| Operating system     | Debian or Microsoft Windows 10

**Comment by schmunk42** [comment]
There's no stable release yet, use `dev-master`.
