### ISSUE TITLE
Add mssql\Schema character_maximum_length support

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/db-mssql#5]
We use mainly MSSQL and do have some trouble with the max-length of some fields. We have to add manually the string `max` rules, to avoid ugly DB errors.

So I thought it would be handy to just add this to the `yii\db\mssql\Schema`, so it would be automatically used by Gii to create the models.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/9400

**Comment by sdlins** [comment]
It was fixed in https://github.com/yiisoft/yii2/pull/17356

**Comment by machour** [comment]
Thank you for the update @sdlins 
The fix needs to be ported to this repo.

**Comment by terabytesoftw** [comment]
Fixed.
