### ISSUE TITLE
Wrong solution for multiple access to DB

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/db-mssql#8]
https://github.com/yiisoft/db-mssql/blob/c3b2eae3c47f719cb9cdec1ba031557e637d797a/src/PDO.php#L26 - it's work only for standalone users:
Example: 2 managers work with base and begin multiple insert into DB. This method return last inserted id, instead id of your new record. 
For correct work need something like this:
~~~
$id = $this->query("SELECT IDENT_CURRENT('{$table}')")->fetchColumn();
$this->exec('INSERT INTO {$table} (name) VALUES ('blabla')');
return $this->query("SELECT {$pk} FROM {$table} WHERE name='blabla' AND {$pk} > {$id}")->fetchColumn();
~~~

**Comment by WinterSilence** [comment]
for understanding read https://docs.microsoft.com/ru-ru/sql/t-sql/functions/scope-identity-transact-sql?view=sql-server-ver15

**Comment by darkdef** [comment]
@WinterSilence may be correct way - exclude this function from SqlsrvPDO ?
```sql
AND {$pk} > {$id}
```
this query return many record with multiple insert

**Comment by darkdef** [comment]
target of function lastInsertId - return last insert id from table - not from current insert session.
For correctly return id from last insert session - need correcting in file Schema.php and remove lines from 983 to 986 and use returning data from OUTPUT INSERTED

```php
foreach ($tableSchema->getPrimaryKey() as $name) {
            if ($tableSchema->getColumns()[$name]->isAutoIncrement()) {
                $result[$name] = $this->getLastInsertID($tableSchema->getSequenceName());
                break;
            }
            /**
             * {@see https://github.com/yiisoft/yii2/issues/13828 & https://github.com/yiisoft/yii2/issues/17474
             */
            if (isset($inserted[$name])) {
                $result[$name] = $inserted[$name];
            } elseif (isset($columns[$name])) {
                $result[$name] = $columns[$name];
            } else {
                $result[$name] = $tableSchema->getColumns()[$name]->getDefaultValue();
            }
        }
```

**Comment by terabytesoftw** [comment]
> target of function lastInsertId - return last insert id from table - not from current insert session.
> For correctly return id from last insert session - need corrected in file Schema.php and remove lines from 983 to 986 and use returning data from OUTPUT INSERTED
> 
> ```
> foreach ($tableSchema->getPrimaryKey() as $name) {
>             if ($tableSchema->getColumns()[$name]->isAutoIncrement()) {
>                 $result[$name] = $this->getLastInsertID($tableSchema->getSequenceName());
>                 break;
>             }
>             /**
>              * {@see https://github.com/yiisoft/yii2/issues/13828 & https://github.com/yiisoft/yii2/issues/17474
>              */
>             if (isset($inserted[$name])) {
>                 $result[$name] = $inserted[$name];
>             } elseif (isset($columns[$name])) {
>                 $result[$name] = $columns[$name];
>             } else {
>                 $result[$name] = $tableSchema->getColumns()[$name]->getDefaultValue();
>             }
>         }
> ```

Can you do the PR to close this issue?

**Comment by darkdef** [comment]
I'can, but may be founded other solution?
More simpled and correct way.
@terabytesoftw - what do you think?

**Comment by terabytesoftw** [comment]
> I'can, but may be founded other solution?
> More simpled and correct way.
> @terabytesoftw - what do you think?

Great idea.

**Comment by WinterSilence** [comment]
@darkdef I'm don't know, I'm explain packages to find solution, but I find only one solution:

1 get last inserted id by `$pk` - `$lastId`
2. insert `$values`
3. find inserted record by `$values` and `$lastId`
~~~php
return $this->query("SELECT {$pk} FROM {$table} WHERE  {$pk} > {$lastId} AND {$insertedValues}")->fetchColumn();
~~~

**Comment by darkdef** [comment]
> 
> 
> @darkdef I'm don't know, I'm explain packages to find solution, but I find only one solution:
> 
> 1 get last inserted id by `$pk` - `$lastId`
> 2. insert `$values`
> 3. find inserted record by `$values` and `$lastId`
> 
> ```
> // generate "where" section, example:
> // $insertedValues = "name='...' AND email='...' AND ...";
> return $this->query("SELECT {$pk} FROM {$table} WHERE {$pk} > {$lastId} AND {$insertedValues}")->fetchColumn();
> ```

With two inserted rows (in parallel), we got incorrect value of pk

**Comment by WinterSilence** [comment]
@darkdef did you use transaction? can you show your test?

**Comment by darkdef** [comment]
Without transaction. That not test - this my assumption.
Correct way get primary key from insert query - use 
```sql
INSERT INTO TABLE (...values...) OUTPUT INSERTED.[pk]
```

**Comment by darkdef** [comment]
@WinterSilence - see my simple solution

**Comment by WinterSilence** [comment]
@darkdef Good solution, but it's work on SQL Server > 2014, need tests. My solution based on rule: every row contain unique data. I didn't found other universal solutions.

**Comment by darkdef** [comment]
Row may don't contain unique data. Solution with `output inserted` correct work with Sql Server 2005 and greater

**Comment by WinterSilence** [comment]
@darkdef hm.. generate error in SQL Server 2008, need check changes.

> An UPDATE, INSERT, or DELETE statement that has an OUTPUT clause will return rows to the client even if the statement encounters errors and is rolled back. The result should not be used if any error occurs when you run the statement.

need check record in table and throw at error

**Comment by darkdef** [comment]
@WinterSilence 
sorry, but i don't understand
Please show example of this case

**Comment by darkdef** [comment]
@WinterSilence - for quick messaging - may be go to tg? search me - darkdef_pr

**Comment by darkdef** [comment]
runnig test with Sql Server 10.0.6556.0 (2008 r1) - test with pk work correctly

**Comment by WinterSilence** [comment]
@darkdef 

> generate error in SQL Server 2008

all fine, my mistake
